package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ KATBEAM_VERSION_ALT }}

source:
  git_url: https://github.com/ska-sa/katbeam.git
  git_rev: 5ce6fcc35471168f4c4b84605cf601d57ced8d9e

build:
  noarch: python
  number: {{ BUILD_NUMBER }}
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ BUILD_NUMBER }}

requirements:
  build:
    - python
    - numpy

  host:
    - python            {{ python }}
    - pip
    - numpy

  run:
    - python            {{ python }}
    - {{ pin_compatible('numpy') }}

about:
  home: https://github.com/i4Ds/katbeam
  license: BSD-License
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'edios - Primary beam modelling of radio astronomy antennas.'
  description: |
    Primary beam model library for the MeerKAT project
  doc_url: https://github.com/i4Ds/katbeam
  dev_url: https://github.com/i4Ds/katbeam

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
