package:
  name: "{{ PACKAGE_NAME|lower }}"
  version: "{{ AOTOOLS_VERSION_ALT }}"

source:
  url: "https://pypi.io/packages/source/{{ PACKAGE_NAME[0] }}/{{ PACKAGE_NAME }}/{{ PACKAGE_NAME }}-{{ AOTOOLS_VERSION }}.tar.gz"

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - python
    - numpy

  host:
    - python                {{ python }}
    - pip
    - numpy

  run:
    - python                {{ python }}
    - matplotlib
    - numba                 >=0.55.1  # 0.53.1 is buggy
    - {{ pin_compatible('numpy') }}
    - scipy                 >=1.10.1

about:
  home: "https://github.com/aotools/aotools"
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: "A set of useful functions for Adaptive Optics in Python"
  doc_url: https://aotools.readthedocs.io/en/v1.0.1/
  dev_url: https://github.com/aotools/aotools

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
