package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ TOOLS_21CM_VERSION_ALT }}

source:
  git_url: "https://github.com/sambit-giri/tools21cm"
  git_rev: "v2.4.3"

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python

  host:
    - python           {{ python }}
    - pip
    - setuptools      >=61
    - wheel
    - cython
    - numpy

  run:
    - python           {{ python }}
    - numpy
    - cython
    - scipy
    - matplotlib
    - astropy
    - scikit-learn
    - scikit-image
    - tqdm
    - joblib
    - pandas
    - openpyxl

about:
  home: "https://github.com/sambit-giri/tools21cm"
  license: MIT
  license_family: MIT
  summary: tools21cm
  description: A python package for analysing 21-cm signals from the Epoch of Reionization (EoR) and Cosmic Dawn (CD).
  doc_url: "https://tools21cm.readthedocs.io/"
  dev_url: "https://github.com/sambit-giri/tools21cm"

extra:
  recipe-maintainers:
    - delberin.ali@fhnw.ch
