package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ TOOLS_21CM_VERSION_ALT }}

source:
  git_url: "https://github.com/sambit-giri/tools21cm"
  git_rev: "39c4197ee2f345361c3a2e2190a576e197caee45"

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - python
    - numpy

  host:
    - python           {{ python }}
    - numpy
    - setuptools

  run:
    - python       {{ python }}
    - astropy
    - joblib
    - matplotlib
    - numba
    - {{ pin_compatible('numpy') }}
    - fftw          =={{ FFTW3_VERSION_ALT }}
    - pyfftw
    - pytest
    - scikit-image
    - scikit-learn
    - scipy         >=1.10.1,<1.15 # see https://github.com/i4Ds/Karabo-Feedstock/issues/30
    - tqdm
    - numexpr
    - tensorflow
    - astroml

about:
  home: "https://github.com/sambit-giri/tools21cm"
  license: MIT
  license_family: MIT
  summary: tools21cm
  description: A python package for analysing 21-cm signals from the Epoch of Reionization (EoR) and Cosmic Dawn (CD).
  doc_url: "https://tools21cm.readthedocs.io/"
  dev_url: "https://github.com/sambit-giri/tools21cm"

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch