{% set sdist_filename = PACKAGE_NAME|replace("-", "_") ~ "-" ~ SKA_SDP_DTMDL_VERSION ~ ".tar.gz" %}  # naming convention needs this

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ SKA_SDP_DTMDL_VERSION_ALT }}

source:
  url: https://artefact.skao.int/repository/pypi-internal/packages/{{ PACKAGE_NAME }}/{{ SKA_SDP_DTMDL_VERSION }}/{{ sdist_filename }}

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}
  script_env:
    - INTERNAL_FOLDER_NAME={{ PACKAGE_NAME|replace("-", "_") }}-{{ SKA_SDP_DTMDL_VERSION }}
  script: bash build.sh

requirements:
  build:
    - python
    - numpy

  host:
    - python            {{ python }}
    - pip
    - numpy
    - poetry-core       >=1.0.0

  run:
    - python            {{ python }}
    - astroplan         >=0.10
    - astropy           >=6.1
    - h5py              >=3.12
    - {{ pin_compatible('numpy') }}
    - pandas            >=2.2
    - xarray            >=2024.9,<2024.11

about:
  home: https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels
  license: Apache 2.0
  license_file: LICENSE
  summary: 'SKA SDP Datamodels'
  description: |
    SKA SDP Datamodels
  doc_url: https://developer.skao.int/projects/ska-sdp-datamodels/en/latest/
  dev_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
