{% set uNameAndVers = PACKAGE_NAME|replace("-", "_") + "-" + SKA_SDP_DTMDL_VERSION %}

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ SKA_SDP_DTMDL_VERSION_ALT }}

source:
  url: https://artefact.skao.int/repository/pypi-internal/packages/{{ PACKAGE_NAME }}/{{ SKA_SDP_DTMDL_VERSION }}/{{ uNameAndVers }}.tar.gz

build:
  number: {{ build }}
  noarch: python
  script_env:
    - INTERNAL_FOLDER_NAME={{ uNameAndVers }}

requirements:
  build:
    - python
    - numpy

  host:
    - python
    - pip
    - numpy
    - poetry-core       >=1.0.0

  run:
    - python                  >=3.10
    - astroplan         >=0.10,<0.11
    - astropy           >=6.1,<7.0
    - h5py              >=3.12,<4.0
    - msgpack-python    >=1.1,<2.0
    - msgpack-numpy     >=0.4.8,<0.5
    - numpy             >=2.2,<2.3
    - pandas            >=2.2,<3.0
    - ska-telmodel      >=1.19,<2.0
    - xarray            >=2024.9

test:
  imports:
    - ska_sdp_datamodels
  commands:
    - python -c "from ska_sdp_datamodels.sky_model.sky_model import SkyComponent"
    - python -c "from ska_sdp_datamodels.configuration.config_create import create_named_configuration"
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels
  license: Apache 2.0
  license_file: LICENSE
  summary: 'SKA SDP Datamodels'
  description: |
    SKA SDP Datamodels
  doc_url: https://developer.skao.int/projects/ska-sdp-datamodels/en/latest/
  dev_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels

extra:
  recipe-maintainers:
    - delberin.ali@fhnw.ch