{% set uNameAndVers = PACKAGE_NAME|replace("-", "_") + "-" + SKA_SDP_DTMDL_VERSION %} # naming convention needs this

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ SKA_SDP_DTMDL_VERSION_ALT }}

source:
   url: https://artefact.skao.int/repository/pypi-internal/packages/{{ PACKAGE_NAME }}/{{ SKA_SDP_DTMDL_VERSION }}/{{ uNameAndVers }}.tar.gz

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}
  script_env:
    - INTERNAL_FOLDER_NAME={{ uNameAndVers }}

requirements:
  build:
    - python
    - numpy

  host:
    - python            {{ python }}
    - pip
    - numpy
    - poetry-core       >=1.0.0

  run:
    - python            {{ python }}
    - astroplan         >=0.8
    - astropy           >=5.1
    - h5py              >=3.7.0
    - {{ pin_compatible('numpy') }}
    - pandas            >=1.5.0
    - xarray            >=2022.10.0

about:
  home: https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels
  license: Apache 2.0
  license_file: {{ uNameAndVers }}/LICENSE
  summary: 'SKA SDP Datamodels'
  description: |
   SKA SDP Datamodels
  doc_url: https://developer.skao.int/projects/ska-sdp-datamodels/en/latest/
  dev_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
