package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ EIDOS_VERSION_ALT }}

source:
  git_url: https://github.com/i4Ds/eidos.git
  git_rev: 74ffe0552079486aef9b413efdf91756096e93e7

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - python
    - numpy

  host:
    - python                  {{ python }}
    - pip
    - numpy

  run:
    - python                  {{ python }}
    - {{ pin_compatible('numpy') }}
    - scipy                   >=1.10.1
    - astropy
    - future

about:
  home: https://github.com/ratt-ru/eidos
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'edios - Primary beam modelling of radio astronomy antennas.'
  description: |
    Primary beam modelling of radio astronomy antennas.
  doc_url: https://github.com/i4Ds/eidos.git
  dev_url: https://github.com/i4Ds/eidos.git

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
