package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ PYBDSF_VERSION_ALT }}

source:
  url: https://pypi.io/packages/source/b/{{ PACKAGE_NAME }}/{{ PACKAGE_NAME }}-{{ PYBDSF_VERSION }}.tar.gz

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - cmake         >=3.18, <4
    - python        {{ python }}
    - numpy         {{ numpy }}
    - boost={{ BOOST_VERSION_ALT }}
    - ninja


  host:
    - python        {{ python }}
    - cmake         >=3.18, <4
    - ninja
    - pip
    - {{ pin_compatible('numpy') }}
    - setuptools    <60.0 # Use <60.0 to avoid setuptools compatibility issues with distutils. distutils is deprecated and it will be removed in Python 3.12., for older version of python it will remain present. this should be changed later for 3.12
    - scikit-build  >=0.13
    - boost={{ BOOST_VERSION_ALT }}
    - wheel

  run:
    - python        {{ python }}
    - boost={{ BOOST_VERSION_ALT }}
    - astropy
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - scipy         >=1.10.1
    - ipython


about:
  home: "https://github.com/lofar-astron/PyBDSF"
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: "Blob Detection and Source Finder"
  doc_url: https://www.astron.nl/citt/pybdsf/
  dev_url: https://github.com/lofar-astron/PyBDSF

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch