package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ RASCIL_VERSION_ALT }}

source:
  git_url: https://gitlab.com/ska-telescope/external/rascil-main
  git_tag: {{ RASCIL_VERSION }}

build:
  noarch: python
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - python
    - curl
    - git-lfs
    - git
    - numpy

  host:
    - python                {{ python }}
    - pip
    - numpy
    - setuptools


  run:
    - python                {{ python }}
    - astropy               >=5.1,      <5.2  # <5.2 for RASCIL <= 1.0 (private import error)
    - bdsf                  ={{ PYBDSF_VERSION_ALT }}
    - dask                  >=2022.12
    - dask-memusage         >=1.1
    - distributed           >=2022.12
    - matplotlib            >=3.6
    - {{ pin_compatible('numpy') }}
    - pandas                >=1.5
    - python-casacore       >=3.5
    - reproject             >=0.9
    - scipy                 >=1.10.1
    - seqfile               >=0.2
    - ska-sdp-datamodels    ={{ SKA_SDP_DTMDL_VERSION_ALT }}
    - ska-sdp-func          ={{ SKA_SDP_FUNC_VERSION_ALT }}
    - ska-sdp-func-python   ={{ SKA_SDP_FUNC_PY_VERSION_ALT }}
    - tabulate              >=0.9
    - xarray                >=2022.12

    
   

about:
  home: https://gitlab.com/ska-telescope/external/rascil-main
  license: APACHE
  license_family: APACHE
  license_file: LICENSE
  summary: 'Radio Astronomy Simulation, Calibration and Imaging Library'
  description: |
    The Radio Astronomy Simulation, Calibration and Imaging Library expresses radio interferometry calibration and imaging algorithms in Python and numpy. The interfaces all operate with familiar data structures such as image, visibility table, gain table, etc. The Python source code is directly accessible from these documentation pages: see the source link in the top right corner.
  doc_url: https://developer.skao.int/projects/rascil/en/latest/index.html
  dev_url: https://gitlab.com/ska-telescope/external/rascil-main

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
