package:
  name: "{{ PACKAGE_NAME|lower }}"
  version: "{{ SEQFILE_VERSION_ALT }}"

source:
  url: "https://pypi.io/packages/source/{{ PACKAGE_NAME[0] }}/{{ PACKAGE_NAME }}/{{ PACKAGE_NAME }}-{{ SEQFILE_VERSION }}.tar.gz"

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}
#  entry_points:
#    - seqfile = seqfile.seqfile:_run

requirements:
  build:
    - python

  host:
    - python        {{ python }}
    - pip

  run:
    - python        {{ python }}
    - natsort       >=3.5.6
    - nose          >=1.0
    - pep8          >=1.6.2

about:
  home: "https://github.com/musically-ut/seqfile"
  license: MIT License or MIT
  license_family: MIT
  license_file:
  summary: "Find the next file in a sequence of files in a thread-safe way."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
