package:
  name: "{{ PACKAGE_NAME|lower }}"
  version: "{{ ARATMOSPY_VERSION_ALT }}"

source:
  git_url: "https://github.com/i4Ds/ARatmospy"
  git_rev: "67c302a136beb40a1cc88b054d7b62ccd927d64f"

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - python
    - numpy

  host:
    - python                  {{ python }}
    - pip
    - numpy

  run:
    - python                  {{ python }}
    - astropy
    - matplotlib
    - {{ pin_compatible('numpy') }}
    - pyfftw
    - scipy                   >=1.9

about:
  home: "https://github.com/i4Ds/ARatmospy"
  license: MIT License or MIT
  license_family: MIT
  license_file:
  summary: "Python version of autoregressive atmosphere generator."
  doc_url: "https://github.com/i4Ds/ARatmospy"
  dev_url: "https://github.com/i4Ds/ARatmospy"

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
