package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ EVERYBEAM_VERSION_ALT }}

source:
  git_url: https://git.astron.nl/RD/EveryBeam.git
  git_rev: 49b61d96785f700cbc200b220478a66b4fedf2d0


build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - boost={{ BOOST_VERSION_ALT }}
    - casacore={{ CASACORE_VERSION_ALT }}
    - cfitsio={{ CFITSIO_VERSION_ALT }}
    - conda-forge::fftw=*=mpi_mpich*
    - hdf5={{ HDF5_VERSION_ALT }}
    - libblas
    - liblapack
    - libxml2
    - python
    - wcslib

  host:
    - boost={{ BOOST_VERSION_ALT }}
    - casacore={{ CASACORE_VERSION_ALT }}
    - cfitsio={{ CFITSIO_VERSION_ALT }}
    - conda-forge::fftw=*=mpi_mpich*
    - hdf5={{ HDF5_VERSION_ALT }}
    - libblas
    - liblapack
    - libxml2
    - python
    - wcslib

  run:
    - boost={{ BOOST_VERSION_ALT }}
    - casacore={{ CASACORE_VERSION_ALT }}
    - cfitsio={{ CFITSIO_VERSION_ALT }}
    - fftw
    - hdf5={{ HDF5_VERSION_ALT }}
    - libblas
    - liblapack
    - libxml2
    - python
    - wcslib

about:
  home: https://everybeam.readthedocs.io
  license: GPLv3
  summary: 'The EveryBeam library is a library that provides the antenna response pattern for several instruments, such as LOFAR (and LOBES), SKA (OSKAR), MWA, JVLA, etc.'
  doc_url: https://everybeam.readthedocs.io
  dev_url: https://git.astron.nl/RD/EveryBeam

extra:
  recipe-maintainers:
    - michel.pluess@fhnw.ch
