package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ environ.get('EVERYBEAM_VERSION_ALT', '0.0.0') }}

source:
  git_url: https://git.astron.nl/RD/EveryBeam.git
  #git_rev: 49b61d96785f700cbc200b220478a66b4fedf2d0
 
  git_tag: "v{{ EVERYBEAM_VERSION }}"

 # patches:
  #  - fix_recursive_lock.patch

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - boost
    - casacore=3.5.0
    - cfitsio
    - conda-forge::fftw=3.3.10=mpi_mpich*
    - hdf5
    - libblas
    - liblapack
    - libxml2
    - python
    - wcslib

  host:
    - boost
    - casacore=3.5.0
    - cfitsio
    - conda-forge::fftw=3.3.10=mpi_mpich*
    - hdf5
    - libblas=
    - liblapack 
    - libxml2
    - python
    - wcslib
  
  run:
    - boost
    - casacore
    - cfitsio
    - fftw
    - hdf5
    - libblas
    - liblapack
    - libxml2
    - python
    - wcslib

about:
  home: https://everybeam.readthedocs.io
  license: GPLv3
  summary: 'The EveryBeam library is a library that provides the antenna response pattern for several instruments, such as LOFAR (and LOBES), SKA (OSKAR), MWA, JVLA, etc.'
  doc_url: https://everybeam.readthedocs.io
  dev_url: https://git.astron.nl/RD/EveryBeam

extra:
  recipe-maintainers:
    - michel.pluess@fhnw.ch
