{% set uNameAndVers = PACKAGE_NAME|replace("-", "_") + "-" + SKA_SDP_FUNC_PY_VERSION %} # naming convention needs this

package:
  name: {{ PACKAGE_NAME|lower }}
  version: {{ SKA_SDP_FUNC_PY_VERSION_ALT }}

source:
   url: https://artefact.skao.int/repository/pypi-internal/packages/{{ PACKAGE_NAME }}/{{ SKA_SDP_FUNC_PY_VERSION }}/{{ uNameAndVers }}.tar.gz

build:
  noarch: python
  number: {{ BUILD_NUMBER }}
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ BUILD_NUMBER }}
  script_env:
    - INTERNAL_FOLDER_NAME={{ uNameAndVers }}
  
requirements:
  build:
    - python
    - numpy

  host:
    - python                {{ python }}
    - poetry-core           >=1.0.0
    - numpy
    
  run:
    - python                {{ python }}
    - astroplan             >=0.8
    - astropy               >=5.1
    - ducc0                 >=0.27.0,       <0.28
    - {{ pin_compatible('numpy') }}
    - photutils             >=1.5
    - scipy                 >=1.10.1
    - ska-sdp-datamodels    =={{ SKA_SDP_DTMDL_VERSION_ALT }}
    - ska-sdp-func          =={{ SKA_SDP_FUNC_VERSION_ALT }}
    - xarray                >=2022.11.0

about:
  home: https://gitlab.com/ska-telescope/sdp/ska-sdp-func-python/
  license: Apache 2.0
  license_file: {{ uNameAndVers }}/LICENSE
  summary: 'SKA SDP Python Processing Functions'
  description: |
   SKA SDP Function Python Wrapper
  doc_url: https://developer.skao.int/projects/ska-sdp-func-python/en/latest/
  dev_url: https://gitlab.com/ska-telescope/sdp/ska-sdp-func-python

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
