name: ARatmospy

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: "main"
        required: true
      dev:
        type: boolean
        required: false
        default: false
      buildNumber:
        type: string
        required: true
      pythonVersions:
        description: "3.12 or 3.11,3.12"
        type: string
        required: true
        default: "3.12"

  workflow_call:
    inputs:
      label:
        type: string
        required: true
      dev:
        type: boolean
        required: false
        default: false
      buildNumber:
        type: string
        required: true
      pythonVersions:
        description: "Python versions, comma-separated"
        type: string
        required: false
        default: "3.12"

jobs:

  Aratmospy:
    uses: ./.github/workflows/build_base.yml
    with:
      packageName: aratmospy
      packageVersion: $ARATMOSPY_VERSION
      packageVersionName: ARATMOSPY_VERSION
      label: ${{ inputs.label }}
      dev: ${{ inputs.dev }}
      buildNumber: ${{ inputs.buildNumber }}
      pythonVersions: ${{ inputs.pythonVersions }}
      pythonCall: import ARatmospy
      isNative: true
    secrets: inherit
